/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "var(--color-background)",
        "bg-soft-200": "var(--color-bg-soft-200)",
        "primary-base": "var(--color-primary-base)",
        "lemon-50": "var(--color-lemon-50)",
        "lemon-500": "var(--color-lemon-500)",
        "lemon-600": "var(--color-lemon-600)",
        "text-strong": "var(--color-text-strong)",
        "text-muted": "var(--color-text-muted)",
        "text-sub-600": "var(--color-text-sub-600)",
        "text-soft-400": "var(--color-text-soft-400)",
        "text-placeholder": "var(--color-text-placeholder)",
        "holly-100": "var(--color-holly-100)",
        "holly-300": "var(--color-holly-300)",
        "holly-400": "var(--color-holly-400)",
        "holly-500": "var(--color-holly-500)",
        "holly-600": "var(--color-holly-600)",
        "holly-700": "var(--color-holly-700)",
        "text-on-primary": "var(--color-text-on-primary)",
        "state-error": "var(--color-state-error)",
        "state-warning": "var(--color-state-warning)",
        "state-success": "var(--color-state-success)",
        "input-bg": "var(--color-input-bg)",
        "input-digit-bg": "var(--color-input-digit-bg)",
        "stroke-soft-200": "var(--color-stroke-soft-200)",
        "button-disabled-bg": "var(--color-button-disabled-bg)",
        "indicator-inactive": "var(--color-indicator-inactive)",
        "glass-border": "var(--color-glass-border)",
        "glass-bg": "var(--color-glass-bg)",
        "radial-glow-start": "var(--color-radial-glow-start)",
        "radial-glow-end": "var(--color-radial-glow-end)",
        "badge-text": "var(--color-badge-text)",
      },
      fontFamily: {
        heuvel: 'var(--font-heuvel)',
        'heuvel-regular': 'var(--font-heuvel-regular)',
      },
    },
  },
  plugins: [],
}
