import { colors } from '../colors';
import { fonts } from '../fonts';

/** Home shell — glow asset, header, and portfolio card layout tokens. */
export const homeShared = {
  topGlow: {
    assetWidth: 430,
    assetHeight: 482,
    widthRatio: 1,
    offsetTop: 0,
  },
  screen: {
    paddingHorizontal: 20,
  },
  header: {
    paddingTop: 29.5,
    avatarSize: 44,
    avatarBorderWidth: 3.385,
    avatarBorderRadius: 9999,
    avatarBorderColor: colors.primary.base,
    avatarBackground: colors.green[950],
    identityGap: 12,
    textGap: 2,
    actionsGap: 16,
    iconColor: colors.text.strong,
    notificationDotColor: colors.state.error,
    name: {
      fontFamily: fonts.heuvelGrotesk,
      fontSize: 24,
      lineHeight: 32,
      letterSpacing: -0.36,
      color: colors.text.strong,
    },
    welcome: {
      fontFamily: fonts.interRegular,
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: -0.176,
      color: colors.text.welcome,
    },
  },
  portfolioCard: {
    marginTop: 31,
    padding: 20,
    gap: 10,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: colors.portfolio.border,
    backgroundColor: colors.portfolio.background,
    innerGap: 16,
    bottomGap: 12,
    label: {
      fontFamily: fonts.inter,
      fontSize: 12,
      fontWeight: '500' as const,
      lineHeight: 16,
      letterSpacing: 0.48,
      color: colors.text.strong,
    },
    amount: {
      fontFamily: fonts.heuvelGrotesk,
      fontSize: 48,
      lineHeight: 56,
      letterSpacing: -0.48,
      color: colors.text.strong,
    },
    amountEyeGap: 8,
    currency: {
      paddingVertical: 4,
      paddingHorizontal: 6,
      gap: 8,
      borderRadius: 12.527,
      backgroundColor: colors.currency.dropdownBackground,
      flagSize: 16,
      text: {
        fontFamily: fonts.inter,
        fontSize: 10,
        fontWeight: '500' as const,
        lineHeight: 16,
        color: colors.text.strong,
      },
    },
    addMoneyWidth: 105,
    chartHeight: 42,
    bottomRowMinHeight: 28,
    statsGap: 12,
    changeBadge: {
      paddingVertical: 2,
      paddingHorizontal: 4,
      gap: 4,
      borderRadius: 24,
      backgroundColor: colors.state.successLighter,
      textColor: colors.state.success,
    },
    changeAmountColor: colors.text.strong,
  },
  quickActions: {
    marginTop: 24,
    gap: 8,
    item: {
      height: 90,
      paddingVertical: 8,
      paddingHorizontal: 12,
      gap: 8,
      borderRadius: 12,
      backgroundColor: colors.holly[600],
      label: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 16,
        lineHeight: 24,
        letterSpacing: -0.176,
        color: colors.text.strong,
      },
    },
  },
  referralBanner: {
    marginTop: 24,
    height: 127,
    padding: 12,
    gap: 10,
    borderRadius: 12,
    gradient: {
      colors: ["rgba(33, 59, 53, 0.49)", "rgba(200, 233, 5, 0.49)"],
      start: { x: 1, y: 0.5 },
      end: { x: 0, y: 0.5 },
    },
    gift: {
      width: 117,
      height: 103,
    },
    title: {
      fontFamily: fonts.heuvelGrotesk,
      fontSize: 18,
      lineHeight: 24,
      letterSpacing: -0.27,
      color: colors.text.strong,
    },
    description: {
      fontFamily: fonts.heuvelGroteskRegular,
      fontSize: 12,
      lineHeight: 16,
      color: colors.holly[50],
    },
    textGap: 4,
    contentGap: 10,
    closeColor: colors.text.strong,
    closeInset: 8,
    pagination: {
      marginTop: 12,
      gap: 6,
      activeWidth: 18,
      activeHeight: 6,
      inactiveSize: 6,
      activeColor: colors.primary.base,
      inactiveColor: colors.holly[400],
    },
  },
  recentTransactions: {
    marginTop: 24,
    headerGap: 12,
    title: {
      fontFamily: fonts.heuvelGrotesk,
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: -0.176,
      color: colors.text.strong,
    },
    seeAll: {
      fontFamily: fonts.heuvelGrotesk,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: -0.084,
      color: colors.lemon[500],
    },
    card: {
      borderRadius: 12,
      backgroundColor: 'rgba(33, 59, 53, 0.40)',
    },
    empty: {
      paddingVertical: 32,
      paddingHorizontal: 12,
      gap: 20,
      walletSize: 88,
      title: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 18,
        lineHeight: 24,
        letterSpacing: -0.27,
        color: colors.text.strong,
      },
      description: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 12,
        lineHeight: 16,
        color: colors.text.soft400,
        maxWidth: 321,
      },
      buttonHeight: 32,
      buttonPadding: 6,
      buttonRadius: 8,
    },
    list: {
      paddingVertical: 24,
      paddingHorizontal: 12,
      gap: 18,
    },
    row: {
      icon: {
        borderRadius: 8.571,
        backgroundColor: colors.holly[600],
        padding: 8,
        arrowSize: 24,
        sentColor: colors.lemon[500],
        receivedColor: colors.lemon[500],
      },
      mainText: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 14,
        lineHeight: 20,
        letterSpacing: -0.084,
        color: colors.text.strong,
      },
      secondaryText: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 12,
        lineHeight: 16,
        color: colors.text.soft400,
      },
      amount: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 14,
        lineHeight: 20,
        letterSpacing: -0.084,
        color: colors.text.strong,
      },
      textGap: 2,
      leftGap: 10,
      badge: {
        paddingVertical: 2,
        paddingHorizontal: 6,
        borderRadius: 24,
        backgroundColor: colors.state.successLighter,
        textColor: colors.state.success,
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 12,
        lineHeight: 16,
      },
    },
    divider: {
      height: 1,
      backgroundColor: colors.holly[600],
    },
  },
} as const;
