import { colors } from "../colors"
import { fonts } from "../fonts"
import { homeShared } from "../home/shared"
import { input } from "../input"
import { typography } from "../typography"

/** Transactions list screen — header, search, and grouped list tokens. */
export const transactionsShared = {
  screen: {
    paddingHorizontal: homeShared.screen.paddingHorizontal,
    paddingTop: homeShared.header.paddingTop,
    sectionGap: 40,
    groupGap: 12,
  },
  header: {
    iconSize: 24,
    iconColor: colors.text.strong,
    title: typography.title.h5,
  },
  search: {
    height: input.height,
    borderRadius: input.borderRadius,
    padding: input.padding,
    gap: input.gap,
    borderColor: colors.holly[600],
    backgroundColor: input.backgroundColor,
    shadow: input.shadow,
    iconSize: 20,
    iconColor: colors.text.strong,
    input: typography.paragraph.input,
    placeholder: typography.paragraph.placeholder,
  },
  dateLabel: {
    fontFamily: fonts.heuvelGrotesk,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: -0.084,
    color: colors.text.strong,
  },
  listCard: homeShared.recentTransactions.card,
  list: homeShared.recentTransactions.list,
  divider: homeShared.recentTransactions.divider,
  filterEmpty: {
    paddingVertical: 32,
    paddingHorizontal: 12,
    gap: 20,
    iconBoxSize: 88,
    iconSize: 40,
    title: {
      fontFamily: fonts.heuvelGrotesk,
      fontSize: 18,
      lineHeight: 24,
      letterSpacing: -0.27,
      color: colors.text.strong,
    },
    description: {
      fontFamily: fonts.heuvelGroteskRegular,
      fontSize: 12,
      lineHeight: 16,
      color: colors.text.soft400,
      maxWidth: 321,
    },
  },
  statusDot: {
    size: 6,
    glowRadius: 4,
    completedColor: colors.state.success,
    failedColor: colors.state.error,
  },
  badge: {
    completed: {
      backgroundColor: colors.state.successLighter,
      textColor: colors.state.success,
    },
    failed: {
      backgroundColor: colors.state.errorLighter,
      textColor: colors.state.error,
    },
  },
  detail: {
    summary: {
      gap: 8,
      padding: 12,
      borderRadius: input.borderRadius,
      borderWidth: 1,
      borderColor: colors.holly[600],
      backgroundColor: input.backgroundColor,
      shadow: input.shadow,
      imageSize: 140,
      label: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 12,
        lineHeight: 16,
        letterSpacing: 0.48,
        color: colors.text.strong,
      },
      amount: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 48,
        lineHeight: 56,
        letterSpacing: -0.48,
        color: colors.text.strong,
      },
      description: {
        fontFamily: fonts.heuvelGroteskRegular,
        fontSize: 14,
        lineHeight: 20,
        letterSpacing: -0.084,
        color: colors.holly[100],
      },
    },
    card: {
      borderRadius: 12,
      backgroundColor: "rgba(33, 59, 53, 0.40)",
      paddingVertical: 24,
      paddingHorizontal: 12,
      gap: 18,
    },
    row: {
      label: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 18,
        lineHeight: 24,
        letterSpacing: -0.27,
        color: colors.holly[300],
      },
      value: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 18,
        lineHeight: 24,
        letterSpacing: -0.27,
        color: colors.text.strong,
      },
    },
    divider: homeShared.recentTransactions.divider,
    actions: {
      gap: 16,
      report: {
        fontFamily: fonts.heuvelGroteskRegular,
        fontSize: 14,
        lineHeight: 20,
        letterSpacing: -0.084,
        color: colors.text.soft400,
        linkColor: colors.lemon[500],
      },
    },
  },
  filter: {
    backgroundColor: "#14241E",
    overlayColor: "rgba(0, 0, 0, 0.55)",
    borderRadius: 24,
    paddingVertical: 26,
    paddingHorizontal: 19,
    gap: 32,
    sectionGap: 32,
    sectionLabelGap: 12,
    tagsGap: 12,
    title: {
      fontFamily: fonts.heuvelGrotesk,
      fontSize: 20,
      lineHeight: 28,
      color: colors.text.strong,
    },
    sectionTitle: {
      fontFamily: fonts.heuvelGrotesk,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: -0.084,
      color: colors.text.strong,
    },
    tag: {
      padding: 8,
      gap: 8,
      borderRadius: input.borderRadius,
      borderColor: colors.holly[600],
      backgroundColor: input.backgroundColor,
      activeBorderColor: colors.lemon[500],
      activeLabelColor: colors.lemon[500],
      shadow: input.shadow,
      label: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 14,
        lineHeight: 20,
        letterSpacing: -0.084,
        color: colors.text.strong,
      },
    },
    date: {
      padding: 8,
      gap: 12,
      iconSize: 20,
      borderRadius: input.borderRadius,
      borderColor: colors.holly[600],
      backgroundColor: input.backgroundColor,
      shadow: input.shadow,
      text: {
        fontFamily: fonts.heuvelGroteskRegular,
        fontSize: 14,
        lineHeight: 20,
        letterSpacing: -0.084,
        color: colors.text.strong,
      },
      placeholder: {
        fontFamily: fonts.heuvelGroteskRegular,
        fontSize: 14,
        lineHeight: 20,
        letterSpacing: -0.084,
        color: colors.text.placeholder,
      },
    },
  },
} as const
