import { colors } from '../colors';
import { fonts } from '../fonts';

/** Per-slide Figma layout — colocated here, not in core design tokens. */
export const onboardingSlides = {
  moneyReceivedCard: {
    width: 303,
    padding: 12,
    contentGap: 12,
    position: {
      bottom: 266,
    },
    sendIcon: {
      backgroundColor: colors.lemon[500],
      paddingTop: 8.05,
      paddingRight: 8.05,
      paddingBottom: 3.45,
      paddingLeft: 3.45,
      borderRadius: 657.143,
      iconSize: 20,
    },
    flagSize: 36,
  },
  walletsPreviewCard: {
    padding: 8,
    gap: 7.142,
    borderRadius: 7.142,
    borderWidth: 0.595,
    position: {
      right: 29,
      bottom: 216,
    },
    row: {
      width: 232.716,
      height: 41.284,
      padding: 7.142,
    },
    lastRow: {
      borderRadius: 7.142,
      backgroundColor: colors.glass.backgroundMuted,
    },
    dividerWidth: 0.595,
    dividerColor: colors.holly[400],
    flagSize: 20,
    rowContentGap: 7.142,
    typography: {
      title: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 10.713,
        fontWeight: 'normal' as const,
        lineHeight: 14.284,
        letterSpacing: -0.161,
        color: colors.text.strong,
      },
      currency: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 10.713,
        fontWeight: 'normal' as const,
        lineHeight: 14.284,
        letterSpacing: -0.161,
        color: colors.text.strong,
      },
      wallet: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 8.333,
        fontWeight: 'normal' as const,
        lineHeight: 11.904,
        letterSpacing: -0.05,
        color: colors.text.soft400,
      },
      amount: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 10.713,
        fontWeight: 'normal' as const,
        lineHeight: 14.284,
        letterSpacing: -0.161,
        color: colors.text.strong,
      },
    },
  },
  convertPreviewCard: {
    width: 248,
    height: 192,
    padding: 8,
    gap: 7.142,
    contentGap: 8,
    borderRadius: 7.142,
    borderWidth: 0.595,
    position: {
      right: 41,
      bottom: 228,
    },
    sourceRow: {
      height: 64.082,
      paddingVertical: 4.747,
      paddingHorizontal: 7.12,
      borderRadius: 7.12,
      borderWidth: 0.593,
      borderColor: colors.primary.base,
      backgroundColor: 'rgba(33, 59, 53, 0.16)',
    },
    targetRow: {
      height: 64.082,
      paddingVertical: 4.747,
      paddingHorizontal: 7.12,
      borderRadius: 7.12,
      backgroundColor: 'rgba(33, 59, 53, 0.16)',
    },
    currencyPill: {
      borderRadius: 7.433,
      backgroundColor: 'rgba(33, 59, 53, 0.40)',
      paddingHorizontal: 5,
      paddingVertical: 3,
      gap: 3,
      iconSize: 10,
      chevronSize: 8,
    },
    swapButton: {
      width: 20,
      height: 20,
      borderRadius: 39.67,
      backgroundColor: colors.holly[500],
      iconSize: 12,
    },
    infoIconSize: 10,
    typography: {
      title: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 10.713,
        fontWeight: 'normal' as const,
        lineHeight: 14.284,
        letterSpacing: -0.161,
        color: colors.text.strong,
      },
      rowLabel: {
        fontFamily: fonts.heuvelGroteskRegular,
        fontSize: 9.494,
        fontWeight: 'normal' as const,
        lineHeight: 14.24,
        letterSpacing: -0.104,
        color: colors.text.soft400,
      },
      balance: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 9.494,
        fontWeight: 'normal' as const,
        lineHeight: 14.24,
        letterSpacing: -0.104,
        color: colors.text.soft400,
      },
      sourceAmount: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 23.734,
        fontWeight: 'normal' as const,
        lineHeight: 28.481,
        letterSpacing: -0.237,
        color: colors.lemon[50],
      },
      targetAmount: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 23.734,
        fontWeight: 'normal' as const,
        lineHeight: 28.481,
        letterSpacing: -0.237,
        color: colors.lemon[500],
      },
      currencyCode: {
        fontFamily: fonts.inter,
        fontSize: 5.934,
        fontWeight: 'normal' as const,
        lineHeight: 9.494,
        color: colors.text.strong,
        textTransform: 'uppercase' as const,
      },
      rateLabel: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 9.494,
        fontWeight: 'normal' as const,
        lineHeight: 14.24,
        letterSpacing: -0.104,
        color: colors.text.soft400,
      },
      rateValue: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 9.494,
        fontWeight: 'normal' as const,
        lineHeight: 14.24,
        letterSpacing: -0.104,
        color: colors.text.strong,
      },
    },
  },
  securityFeaturesCard: {
    width: 387,
    height: 195.569,
    screenPaddingLeft: 20,
    position: {
      right: 23,
      bottom: 230,
    },
    card: {
      width: 280,
      height: 54,
      padding: 7.142,
      gap: 7.142,
      borderRadius: 7.142,
      borderWidth: 0.595,
    },
    icon: {
      width: 24,
      height: 24,
      paddingTop: 4.125,
      paddingRight: 4.281,
      paddingBottom: 3.875,
      paddingLeft: 3.719,
      borderRadius: 340.143,
      backgroundColor: colors.lemon[500],
      iconSize: 14,
    },
    tag: {
      borderRadius: 200,
      borderWidth: 0.6,
      borderColor: colors.glass.border,
      backgroundColor: 'rgba(114, 130, 21, 0.20)',
      paddingHorizontal: 8,
      paddingVertical: 4,
      gap: 4,
      iconSize: 12,
    },
    typography: {
      primary: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 10.713,
        fontWeight: 'normal' as const,
        lineHeight: 14.284,
        letterSpacing: -0.161,
        color: colors.text.strong,
      },
      secondary: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 8.333,
        fontWeight: 'normal' as const,
        lineHeight: 11.904,
        letterSpacing: -0.05,
        color: colors.text.soft400,
      },
      tag: {
        fontFamily: fonts.heuvelGrotesk,
        fontSize: 10.713,
        fontWeight: 'normal' as const,
        lineHeight: 14.284,
        letterSpacing: -0.161,
        color: colors.lemon[500],
      },
    },
  },
} as const;
